### ISSUE TITLE
unscoped package name is available

### ISSUE THREAD

**Issue by magicdawn** [ElasticBottle/trpc-post-message#7]
see https://www.npmjs.com/package/trpc-post-message 

unscoped package name is available, would u like to publish without `@scope/`, since your username is pretty long :)

just a advice

**Comment by ElasticBottle** [comment]
Cool, thanks for flagging this out!

Might republish again in the future, but no plans right now. I believe most people copy and paste the package name to install anyways so that shouldn't be too big of an issue
